//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace CDWKS.Social.Taco.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class CDWKS_SocialFeedbackEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new CDWKS_SocialFeedbackEntities object using the connection string found in the 'CDWKS_SocialFeedbackEntities' section of the application configuration file.
        /// </summary>
        public CDWKS_SocialFeedbackEntities() : base("name=CDWKS_SocialFeedbackEntities", "CDWKS_SocialFeedbackEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new CDWKS_SocialFeedbackEntities object.
        /// </summary>
        public CDWKS_SocialFeedbackEntities(string connectionString) : base(connectionString, "CDWKS_SocialFeedbackEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new CDWKS_SocialFeedbackEntities object.
        /// </summary>
        public CDWKS_SocialFeedbackEntities(EntityConnection connection) : base(connection, "CDWKS_SocialFeedbackEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<SocialFeedbackForm> SocialFeedbackForms
        {
            get
            {
                if ((_SocialFeedbackForms == null))
                {
                    _SocialFeedbackForms = base.CreateObjectSet<SocialFeedbackForm>("SocialFeedbackForms");
                }
                return _SocialFeedbackForms;
            }
        }
        private ObjectSet<SocialFeedbackForm> _SocialFeedbackForms;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the SocialFeedbackForms EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSocialFeedbackForms(SocialFeedbackForm socialFeedbackForm)
        {
            base.AddObject("SocialFeedbackForms", socialFeedbackForm);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CDWKS_SocialFeedbackModel", Name="SocialFeedbackForm")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class SocialFeedbackForm : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new SocialFeedbackForm object.
        /// </summary>
        /// <param name="socialFeebackFormId">Initial value of the SocialFeebackFormId property.</param>
        /// <param name="username">Initial value of the Username property.</param>
        /// <param name="email">Initial value of the Email property.</param>
        /// <param name="product">Initial value of the Product property.</param>
        /// <param name="family">Initial value of the Family property.</param>
        /// <param name="like">Initial value of the Like property.</param>
        /// <param name="comments">Initial value of the Comments property.</param>
        /// <param name="timestamp">Initial value of the Timestamp property.</param>
        public static SocialFeedbackForm CreateSocialFeedbackForm(global::System.Int32 socialFeebackFormId, global::System.String username, global::System.String email, global::System.String product, global::System.String family, global::System.Boolean like, global::System.String comments, global::System.DateTime timestamp)
        {
            SocialFeedbackForm socialFeedbackForm = new SocialFeedbackForm();
            socialFeedbackForm.SocialFeebackFormId = socialFeebackFormId;
            socialFeedbackForm.Username = username;
            socialFeedbackForm.Email = email;
            socialFeedbackForm.Product = product;
            socialFeedbackForm.Family = family;
            socialFeedbackForm.Like = like;
            socialFeedbackForm.Comments = comments;
            socialFeedbackForm.Timestamp = timestamp;
            return socialFeedbackForm;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SocialFeebackFormId
        {
            get
            {
                return _SocialFeebackFormId;
            }
            set
            {
                if (_SocialFeebackFormId != value)
                {
                    OnSocialFeebackFormIdChanging(value);
                    ReportPropertyChanging("SocialFeebackFormId");
                    _SocialFeebackFormId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("SocialFeebackFormId");
                    OnSocialFeebackFormIdChanged();
                }
            }
        }
        private global::System.Int32 _SocialFeebackFormId;
        partial void OnSocialFeebackFormIdChanging(global::System.Int32 value);
        partial void OnSocialFeebackFormIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Username
        {
            get
            {
                return _Username;
            }
            set
            {
                OnUsernameChanging(value);
                ReportPropertyChanging("Username");
                _Username = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Username");
                OnUsernameChanged();
            }
        }
        private global::System.String _Username;
        partial void OnUsernameChanging(global::System.String value);
        partial void OnUsernameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FirstName
        {
            get
            {
                return _FirstName;
            }
            set
            {
                OnFirstNameChanging(value);
                ReportPropertyChanging("FirstName");
                _FirstName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FirstName");
                OnFirstNameChanged();
            }
        }
        private global::System.String _FirstName;
        partial void OnFirstNameChanging(global::System.String value);
        partial void OnFirstNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LastName
        {
            get
            {
                return _LastName;
            }
            set
            {
                OnLastNameChanging(value);
                ReportPropertyChanging("LastName");
                _LastName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LastName");
                OnLastNameChanged();
            }
        }
        private global::System.String _LastName;
        partial void OnLastNameChanging(global::System.String value);
        partial void OnLastNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Company
        {
            get
            {
                return _Company;
            }
            set
            {
                OnCompanyChanging(value);
                ReportPropertyChanging("Company");
                _Company = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Company");
                OnCompanyChanged();
            }
        }
        private global::System.String _Company;
        partial void OnCompanyChanging(global::System.String value);
        partial void OnCompanyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Product
        {
            get
            {
                return _Product;
            }
            set
            {
                OnProductChanging(value);
                ReportPropertyChanging("Product");
                _Product = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Product");
                OnProductChanged();
            }
        }
        private global::System.String _Product;
        partial void OnProductChanging(global::System.String value);
        partial void OnProductChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Family
        {
            get
            {
                return _Family;
            }
            set
            {
                OnFamilyChanging(value);
                ReportPropertyChanging("Family");
                _Family = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Family");
                OnFamilyChanged();
            }
        }
        private global::System.String _Family;
        partial void OnFamilyChanging(global::System.String value);
        partial void OnFamilyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Like
        {
            get
            {
                return _Like;
            }
            set
            {
                OnLikeChanging(value);
                ReportPropertyChanging("Like");
                _Like = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Like");
                OnLikeChanged();
            }
        }
        private global::System.Boolean _Like;
        partial void OnLikeChanging(global::System.Boolean value);
        partial void OnLikeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Comments
        {
            get
            {
                return _Comments;
            }
            set
            {
                OnCommentsChanging(value);
                ReportPropertyChanging("Comments");
                _Comments = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Comments");
                OnCommentsChanged();
            }
        }
        private global::System.String _Comments;
        partial void OnCommentsChanging(global::System.String value);
        partial void OnCommentsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Timestamp
        {
            get
            {
                return _Timestamp;
            }
            set
            {
                OnTimestampChanging(value);
                ReportPropertyChanging("Timestamp");
                _Timestamp = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Timestamp");
                OnTimestampChanged();
            }
        }
        private global::System.DateTime _Timestamp;
        partial void OnTimestampChanging(global::System.DateTime value);
        partial void OnTimestampChanged();

        #endregion
    
    }

    #endregion
    
}
