//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Original file name:
// Generation date: 1/16/2012 9:08:59 PM

using System;

namespace CDWKS.BXC.Taco.Web.UserService
{
    
    /// <summary>
    /// There are no comments for BXC_MasterControlEntities in the schema.
    /// </summary>
    public partial class BXC_MasterControlEntities : global::System.Data.Services.Client.DataServiceContext, IDisposable
    {
        /// <summary>
        /// Initialize a new BXC_MasterControlEntities object.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public BXC_MasterControlEntities(global::System.Uri serviceRoot) : 
                base(serviceRoot)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            if (typeName.StartsWith("BXC_MasterControlModel", global::System.StringComparison.Ordinal))
            {
                return this.GetType().Assembly.GetType(string.Concat("CDWKS.BXC.Taco.Web.UserService", typeName.Substring(22)), false);
            }
            return null;
        }
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            if (clientType.Namespace.Equals("CDWKS.BXC.Taco.Web.UserService", global::System.StringComparison.Ordinal))
            {
                return string.Concat("BXC_MasterControlModel.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// There are no comments for Downloads in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Download> Downloads
        {
            get
            {
                if ((this._Downloads == null))
                {
                    this._Downloads = base.CreateQuery<Download>("Downloads");
                }
                return this._Downloads;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Download> _Downloads;
        /// <summary>
        /// There are no comments for ExtendedProperties in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<ExtendedProperty> ExtendedProperties
        {
            get
            {
                if ((this._ExtendedProperties == null))
                {
                    this._ExtendedProperties = base.CreateQuery<ExtendedProperty>("ExtendedProperties");
                }
                return this._ExtendedProperties;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<ExtendedProperty> _ExtendedProperties;
        /// <summary>
        /// There are no comments for Libraries in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Library> Libraries
        {
            get
            {
                if ((this._Libraries == null))
                {
                    this._Libraries = base.CreateQuery<Library>("Libraries");
                }
                return this._Libraries;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Library> _Libraries;
        /// <summary>
        /// There are no comments for Licenses in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<License> Licenses
        {
            get
            {
                if ((this._Licenses == null))
                {
                    this._Licenses = base.CreateQuery<License>("Licenses");
                }
                return this._Licenses;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<License> _Licenses;
        /// <summary>
        /// There are no comments for LicenseTypes in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<LicenseType> LicenseTypes
        {
            get
            {
                if ((this._LicenseTypes == null))
                {
                    this._LicenseTypes = base.CreateQuery<LicenseType>("LicenseTypes");
                }
                return this._LicenseTypes;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<LicenseType> _LicenseTypes;
        /// <summary>
        /// There are no comments for Owners in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Owner> Owners
        {
            get
            {
                if ((this._Owners == null))
                {
                    this._Owners = base.CreateQuery<Owner>("Owners");
                }
                return this._Owners;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Owner> _Owners;
        /// <summary>
        /// There are no comments for PropertyNames in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<PropertyName> PropertyNames
        {
            get
            {
                if ((this._PropertyNames == null))
                {
                    this._PropertyNames = base.CreateQuery<PropertyName>("PropertyNames");
                }
                return this._PropertyNames;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<PropertyName> _PropertyNames;
        /// <summary>
        /// There are no comments for PropertyValues in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<PropertyValue> PropertyValues
        {
            get
            {
                if ((this._PropertyValues == null))
                {
                    this._PropertyValues = base.CreateQuery<PropertyValue>("PropertyValues");
                }
                return this._PropertyValues;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<PropertyValue> _PropertyValues;
        /// <summary>
        /// There are no comments for UserLibraries in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<UserLibrary> UserLibraries
        {
            get
            {
                if ((this._UserLibraries == null))
                {
                    this._UserLibraries = base.CreateQuery<UserLibrary>("UserLibraries");
                }
                return this._UserLibraries;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<UserLibrary> _UserLibraries;
        /// <summary>
        /// There are no comments for Users in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<User> Users
        {
            get
            {
                if ((this._Users == null))
                {
                    this._Users = base.CreateQuery<User>("Users");
                }
                return this._Users;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<User> _Users;
        /// <summary>
        /// There are no comments for Downloads in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToDownloads(Download download)
        {
            base.AddObject("Downloads", download);
        }
        /// <summary>
        /// There are no comments for ExtendedProperties in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToExtendedProperties(ExtendedProperty extendedProperty)
        {
            base.AddObject("ExtendedProperties", extendedProperty);
        }
        /// <summary>
        /// There are no comments for Libraries in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToLibraries(Library library)
        {
            base.AddObject("Libraries", library);
        }
        /// <summary>
        /// There are no comments for Licenses in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToLicenses(License license)
        {
            base.AddObject("Licenses", license);
        }
        /// <summary>
        /// There are no comments for LicenseTypes in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToLicenseTypes(LicenseType licenseType)
        {
            base.AddObject("LicenseTypes", licenseType);
        }
        /// <summary>
        /// There are no comments for Owners in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToOwners(Owner owner)
        {
            base.AddObject("Owners", owner);
        }
        /// <summary>
        /// There are no comments for PropertyNames in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToPropertyNames(PropertyName propertyName)
        {
            base.AddObject("PropertyNames", propertyName);
        }
        /// <summary>
        /// There are no comments for PropertyValues in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToPropertyValues(PropertyValue propertyValue)
        {
            base.AddObject("PropertyValues", propertyValue);
        }
        /// <summary>
        /// There are no comments for UserLibraries in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToUserLibraries(UserLibrary userLibrary)
        {
            base.AddObject("UserLibraries", userLibrary);
        }
        /// <summary>
        /// There are no comments for Users in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToUsers(User user)
        {
            base.AddObject("Users", user);
        }

        public void Dispose()
        {
          
        }
    }
    /// <summary>
    /// There are no comments for BXC_MasterControlModel.Download in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class Download
    {
        /// <summary>
        /// Create a new Download object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="content_Id">Initial value of Content_Id.</param>
        /// <param name="dateTime">Initial value of DateTime.</param>
        /// <param name="user_Id">Initial value of User_Id.</param>
        /// <param name="library_Id">Initial value of Library_Id.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Download CreateDownload(int ID, string content_Id, global::System.DateTime dateTime, int user_Id, int library_Id)
        {
            Download download = new Download();
            download.Id = ID;
            download.Content_Id = content_Id;
            download.DateTime = dateTime;
            download.User_Id = user_Id;
            download.Library_Id = library_Id;
            return download;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Content_Id in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Content_Id
        {
            get
            {
                return this._Content_Id;
            }
            set
            {
                this.OnContent_IdChanging(value);
                this._Content_Id = value;
                this.OnContent_IdChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Content_Id;
        partial void OnContent_IdChanging(string value);
        partial void OnContent_IdChanged();
        /// <summary>
        /// There are no comments for Property DateTime in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime DateTime
        {
            get
            {
                return this._DateTime;
            }
            set
            {
                this.OnDateTimeChanging(value);
                this._DateTime = value;
                this.OnDateTimeChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _DateTime;
        partial void OnDateTimeChanging(global::System.DateTime value);
        partial void OnDateTimeChanged();
        /// <summary>
        /// There are no comments for Property User_Id in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int User_Id
        {
            get
            {
                return this._User_Id;
            }
            set
            {
                this.OnUser_IdChanging(value);
                this._User_Id = value;
                this.OnUser_IdChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _User_Id;
        partial void OnUser_IdChanging(int value);
        partial void OnUser_IdChanged();
        /// <summary>
        /// There are no comments for Property Library_Id in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Library_Id
        {
            get
            {
                return this._Library_Id;
            }
            set
            {
                this.OnLibrary_IdChanging(value);
                this._Library_Id = value;
                this.OnLibrary_IdChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Library_Id;
        partial void OnLibrary_IdChanging(int value);
        partial void OnLibrary_IdChanged();
        /// <summary>
        /// There are no comments for Library in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Library Library
        {
            get
            {
                return this._Library;
            }
            set
            {
                this._Library = value;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Library _Library;
        /// <summary>
        /// There are no comments for User in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public User User
        {
            get
            {
                return this._User;
            }
            set
            {
                this._User = value;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private User _User;
    }
    /// <summary>
    /// There are no comments for BXC_MasterControlModel.ExtendedProperty in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class ExtendedProperty
    {
        /// <summary>
        /// Create a new ExtendedProperty object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="user_Id">Initial value of User_Id.</param>
        /// <param name="propertyNames_Id">Initial value of PropertyNames_Id.</param>
        /// <param name="propertyValues_Id">Initial value of PropertyValues_Id.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static ExtendedProperty CreateExtendedProperty(int ID, int user_Id, int propertyNames_Id, int propertyValues_Id)
        {
            ExtendedProperty extendedProperty = new ExtendedProperty();
            extendedProperty.Id = ID;
            extendedProperty.User_Id = user_Id;
            extendedProperty.PropertyNames_Id = propertyNames_Id;
            extendedProperty.PropertyValues_Id = propertyValues_Id;
            return extendedProperty;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property User_Id in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int User_Id
        {
            get
            {
                return this._User_Id;
            }
            set
            {
                this.OnUser_IdChanging(value);
                this._User_Id = value;
                this.OnUser_IdChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _User_Id;
        partial void OnUser_IdChanging(int value);
        partial void OnUser_IdChanged();
        /// <summary>
        /// There are no comments for Property PropertyNames_Id in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int PropertyNames_Id
        {
            get
            {
                return this._PropertyNames_Id;
            }
            set
            {
                this.OnPropertyNames_IdChanging(value);
                this._PropertyNames_Id = value;
                this.OnPropertyNames_IdChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _PropertyNames_Id;
        partial void OnPropertyNames_IdChanging(int value);
        partial void OnPropertyNames_IdChanged();
        /// <summary>
        /// There are no comments for Property PropertyValues_Id in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int PropertyValues_Id
        {
            get
            {
                return this._PropertyValues_Id;
            }
            set
            {
                this.OnPropertyValues_IdChanging(value);
                this._PropertyValues_Id = value;
                this.OnPropertyValues_IdChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _PropertyValues_Id;
        partial void OnPropertyValues_IdChanging(int value);
        partial void OnPropertyValues_IdChanged();
        /// <summary>
        /// There are no comments for PropertyName in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public PropertyName PropertyName
        {
            get
            {
                return this._PropertyName;
            }
            set
            {
                this._PropertyName = value;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private PropertyName _PropertyName;
        /// <summary>
        /// There are no comments for PropertyValue in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public PropertyValue PropertyValue
        {
            get
            {
                return this._PropertyValue;
            }
            set
            {
                this._PropertyValue = value;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private PropertyValue _PropertyValue;
        /// <summary>
        /// There are no comments for User in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public User User
        {
            get
            {
                return this._User;
            }
            set
            {
                this._User = value;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private User _User;
    }
    /// <summary>
    /// There are no comments for BXC_MasterControlModel.Library in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class Library
    {
        /// <summary>
        /// Create a new Library object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="name">Initial value of Name.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Library CreateLibrary(int ID, string name)
        {
            Library library = new Library();
            library.Id = ID;
            library.Name = name;
            return library;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Downloads in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Collections.ObjectModel.Collection<Download> Downloads
        {
            get
            {
                return this._Downloads;
            }
            set
            {
                if ((value != null))
                {
                    this._Downloads = value;
                }
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Collections.ObjectModel.Collection<Download> _Downloads = new global::System.Collections.ObjectModel.Collection<Download>();
        /// <summary>
        /// There are no comments for Licenses in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Collections.ObjectModel.Collection<License> Licenses
        {
            get
            {
                return this._Licenses;
            }
            set
            {
                if ((value != null))
                {
                    this._Licenses = value;
                }
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Collections.ObjectModel.Collection<License> _Licenses = new global::System.Collections.ObjectModel.Collection<License>();
    }
    /// <summary>
    /// There are no comments for BXC_MasterControlModel.License in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class License
    {
        /// <summary>
        /// Create a new License object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="authCode">Initial value of AuthCode.</param>
        /// <param name="maxUsers">Initial value of MaxUsers.</param>
        /// <param name="owners_Id">Initial value of Owners_Id.</param>
        /// <param name="licenseType_Id">Initial value of LicenseType_Id.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static License CreateLicense(int ID, string authCode, long maxUsers, int owners_Id, int licenseType_Id)
        {
            License license = new License();
            license.Id = ID;
            license.AuthCode = authCode;
            license.MaxUsers = maxUsers;
            license.Owners_Id = owners_Id;
            license.LicenseType_Id = licenseType_Id;
            return license;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property AuthCode in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string AuthCode
        {
            get
            {
                return this._AuthCode;
            }
            set
            {
                this.OnAuthCodeChanging(value);
                this._AuthCode = value;
                this.OnAuthCodeChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _AuthCode;
        partial void OnAuthCodeChanging(string value);
        partial void OnAuthCodeChanged();
        /// <summary>
        /// There are no comments for Property MaxUsers in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public long MaxUsers
        {
            get
            {
                return this._MaxUsers;
            }
            set
            {
                this.OnMaxUsersChanging(value);
                this._MaxUsers = value;
                this.OnMaxUsersChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private long _MaxUsers;
        partial void OnMaxUsersChanging(long value);
        partial void OnMaxUsersChanged();
        /// <summary>
        /// There are no comments for Property Owners_Id in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Owners_Id
        {
            get
            {
                return this._Owners_Id;
            }
            set
            {
                this.OnOwners_IdChanging(value);
                this._Owners_Id = value;
                this.OnOwners_IdChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Owners_Id;
        partial void OnOwners_IdChanging(int value);
        partial void OnOwners_IdChanged();
        /// <summary>
        /// There are no comments for Property LicenseType_Id in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int LicenseType_Id
        {
            get
            {
                return this._LicenseType_Id;
            }
            set
            {
                this.OnLicenseType_IdChanging(value);
                this._LicenseType_Id = value;
                this.OnLicenseType_IdChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _LicenseType_Id;
        partial void OnLicenseType_IdChanging(int value);
        partial void OnLicenseType_IdChanged();
        /// <summary>
        /// There are no comments for Owner in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Owner Owner
        {
            get
            {
                return this._Owner;
            }
            set
            {
                this._Owner = value;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Owner _Owner;
        /// <summary>
        /// There are no comments for LicenseType in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public LicenseType LicenseType
        {
            get
            {
                return this._LicenseType;
            }
            set
            {
                this._LicenseType = value;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private LicenseType _LicenseType;
        /// <summary>
        /// There are no comments for Libraries in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Collections.ObjectModel.Collection<Library> Libraries
        {
            get
            {
                return this._Libraries;
            }
            set
            {
                if ((value != null))
                {
                    this._Libraries = value;
                }
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Collections.ObjectModel.Collection<Library> _Libraries = new global::System.Collections.ObjectModel.Collection<Library>();
    }
    /// <summary>
    /// There are no comments for BXC_MasterControlModel.LicenseType in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class LicenseType
    {
        /// <summary>
        /// Create a new LicenseType object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="name">Initial value of Name.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static LicenseType CreateLicenseType(int ID, string name)
        {
            LicenseType licenseType = new LicenseType();
            licenseType.Id = ID;
            licenseType.Name = name;
            return licenseType;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Licenses in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Collections.ObjectModel.Collection<License> Licenses
        {
            get
            {
                return this._Licenses;
            }
            set
            {
                if ((value != null))
                {
                    this._Licenses = value;
                }
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Collections.ObjectModel.Collection<License> _Licenses = new global::System.Collections.ObjectModel.Collection<License>();
    }
    /// <summary>
    /// There are no comments for BXC_MasterControlModel.Owner in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class Owner
    {
        /// <summary>
        /// Create a new Owner object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="name">Initial value of Name.</param>
        /// <param name="createdDate">Initial value of CreatedDate.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Owner CreateOwner(int ID, string name, global::System.DateTime createdDate)
        {
            Owner owner = new Owner();
            owner.Id = ID;
            owner.Name = name;
            owner.CreatedDate = createdDate;
            return owner;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property CreatedDate in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime CreatedDate
        {
            get
            {
                return this._CreatedDate;
            }
            set
            {
                this.OnCreatedDateChanging(value);
                this._CreatedDate = value;
                this.OnCreatedDateChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _CreatedDate;
        partial void OnCreatedDateChanging(global::System.DateTime value);
        partial void OnCreatedDateChanged();
        /// <summary>
        /// There are no comments for Licenses in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Collections.ObjectModel.Collection<License> Licenses
        {
            get
            {
                return this._Licenses;
            }
            set
            {
                if ((value != null))
                {
                    this._Licenses = value;
                }
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Collections.ObjectModel.Collection<License> _Licenses = new global::System.Collections.ObjectModel.Collection<License>();
    }
    /// <summary>
    /// There are no comments for BXC_MasterControlModel.PropertyName in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class PropertyName
    {
        /// <summary>
        /// Create a new PropertyName object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="name">Initial value of Name.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static PropertyName CreatePropertyName(int ID, string name)
        {
            PropertyName propertyName = new PropertyName();
            propertyName.Id = ID;
            propertyName.Name = name;
            return propertyName;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for ExtendedProperties in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Collections.ObjectModel.Collection<ExtendedProperty> ExtendedProperties
        {
            get
            {
                return this._ExtendedProperties;
            }
            set
            {
                if ((value != null))
                {
                    this._ExtendedProperties = value;
                }
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Collections.ObjectModel.Collection<ExtendedProperty> _ExtendedProperties = new global::System.Collections.ObjectModel.Collection<ExtendedProperty>();
    }
    /// <summary>
    /// There are no comments for BXC_MasterControlModel.PropertyValue in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class PropertyValue
    {
        /// <summary>
        /// Create a new PropertyValue object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="value">Initial value of Value.</param>
        /// <param name="extendedProperty_Id">Initial value of ExtendedProperty_Id.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static PropertyValue CreatePropertyValue(int ID, string value, int extendedProperty_Id)
        {
            PropertyValue propertyValue = new PropertyValue();
            propertyValue.Id = ID;
            propertyValue.Value = value;
            propertyValue.ExtendedProperty_Id = extendedProperty_Id;
            return propertyValue;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Value in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Value
        {
            get
            {
                return this._Value;
            }
            set
            {
                this.OnValueChanging(value);
                this._Value = value;
                this.OnValueChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Value;
        partial void OnValueChanging(string value);
        partial void OnValueChanged();
        /// <summary>
        /// There are no comments for Property ExtendedProperty_Id in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int ExtendedProperty_Id
        {
            get
            {
                return this._ExtendedProperty_Id;
            }
            set
            {
                this.OnExtendedProperty_IdChanging(value);
                this._ExtendedProperty_Id = value;
                this.OnExtendedProperty_IdChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _ExtendedProperty_Id;
        partial void OnExtendedProperty_IdChanging(int value);
        partial void OnExtendedProperty_IdChanged();
        /// <summary>
        /// There are no comments for ExtendedProperties in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Collections.ObjectModel.Collection<ExtendedProperty> ExtendedProperties
        {
            get
            {
                return this._ExtendedProperties;
            }
            set
            {
                if ((value != null))
                {
                    this._ExtendedProperties = value;
                }
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Collections.ObjectModel.Collection<ExtendedProperty> _ExtendedProperties = new global::System.Collections.ObjectModel.Collection<ExtendedProperty>();
    }
    /// <summary>
    /// There are no comments for BXC_MasterControlModel.UserLibrary in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class UserLibrary
    {
        /// <summary>
        /// Create a new UserLibrary object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="userId">Initial value of UserId.</param>
        /// <param name="libraryId">Initial value of LibraryId.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static UserLibrary CreateUserLibrary(int ID, int userId, int libraryId)
        {
            UserLibrary userLibrary = new UserLibrary();
            userLibrary.Id = ID;
            userLibrary.UserId = userId;
            userLibrary.LibraryId = libraryId;
            return userLibrary;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property UserId in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int UserId
        {
            get
            {
                return this._UserId;
            }
            set
            {
                this.OnUserIdChanging(value);
                this._UserId = value;
                this.OnUserIdChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _UserId;
        partial void OnUserIdChanging(int value);
        partial void OnUserIdChanged();
        /// <summary>
        /// There are no comments for Property LibraryId in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int LibraryId
        {
            get
            {
                return this._LibraryId;
            }
            set
            {
                this.OnLibraryIdChanging(value);
                this._LibraryId = value;
                this.OnLibraryIdChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _LibraryId;
        partial void OnLibraryIdChanging(int value);
        partial void OnLibraryIdChanged();
    }
    /// <summary>
    /// There are no comments for BXC_MasterControlModel.User in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class User
    {
        /// <summary>
        /// Create a new User object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="userName">Initial value of UserName.</param>
        /// <param name="password">Initial value of Password.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static User CreateUser(int ID, string userName, string password)
        {
            User user = new User();
            user.Id = ID;
            user.UserName = userName;
            user.Password = password;
            return user;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property UserName in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string UserName
        {
            get
            {
                return this._UserName;
            }
            set
            {
                this.OnUserNameChanging(value);
                this._UserName = value;
                this.OnUserNameChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _UserName;
        partial void OnUserNameChanging(string value);
        partial void OnUserNameChanged();
        /// <summary>
        /// There are no comments for Property Password in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Password
        {
            get
            {
                return this._Password;
            }
            set
            {
                this.OnPasswordChanging(value);
                this._Password = value;
                this.OnPasswordChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Password;
        partial void OnPasswordChanging(string value);
        partial void OnPasswordChanged();
        /// <summary>
        /// There are no comments for Downloads in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Collections.ObjectModel.Collection<Download> Downloads
        {
            get
            {
                return this._Downloads;
            }
            set
            {
                if ((value != null))
                {
                    this._Downloads = value;
                }
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Collections.ObjectModel.Collection<Download> _Downloads = new global::System.Collections.ObjectModel.Collection<Download>();
        /// <summary>
        /// There are no comments for ExtendedProperties in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Collections.ObjectModel.Collection<ExtendedProperty> ExtendedProperties
        {
            get
            {
                return this._ExtendedProperties;
            }
            set
            {
                if ((value != null))
                {
                    this._ExtendedProperties = value;
                }
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Collections.ObjectModel.Collection<ExtendedProperty> _ExtendedProperties = new global::System.Collections.ObjectModel.Collection<ExtendedProperty>();
    }
}
