//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDWKS.RevitAddon.Indexer2012.RevitFileServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RevitFileServiceReference.IAutodeskFileService")]
    public interface IAutodeskFileService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutodeskFileService/IndexAutodeskFile", ReplyAction="http://tempuri.org/IAutodeskFileService/IndexAutodeskFileResponse")]
        CDWKS.RevitAddon.Indexer2012.RevitFileServiceReference.IndexAutodeskFileResponse IndexAutodeskFile(CDWKS.RevitAddon.Indexer2012.RevitFileServiceReference.IndexAutodeskFileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutodeskFileService/AddTypeToFile", ReplyAction="http://tempuri.org/IAutodeskFileService/AddTypeToFileResponse")]
        CDWKS.RevitAddon.Indexer2012.RevitFileServiceReference.AddTypeToFileResponse AddTypeToFile(CDWKS.RevitAddon.Indexer2012.RevitFileServiceReference.AddTypeToFileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutodeskFileService/UpdateLibraryTreeView", ReplyAction="http://tempuri.org/IAutodeskFileService/UpdateLibraryTreeViewResponse")]
        CDWKS.RevitAddon.Indexer2012.RevitFileServiceReference.UpdateLibraryTreeViewResponse UpdateLibraryTreeView(CDWKS.RevitAddon.Indexer2012.RevitFileServiceReference.UpdateLibraryTreeViewRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutodeskFileService/GetAutodeskFile", ReplyAction="http://tempuri.org/IAutodeskFileService/GetAutodeskFileResponse")]
        CDWKS.RevitAddon.Indexer2012.RevitFileServiceReference.GetAutodeskFileResponse GetAutodeskFile(CDWKS.RevitAddon.Indexer2012.RevitFileServiceReference.GetAutodeskFileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutodeskFileService/GetContentLibrary", ReplyAction="http://tempuri.org/IAutodeskFileService/GetContentLibraryResponse")]
        CDWKS.RevitAddon.Indexer2012.RevitFileServiceReference.GetContentLibraryResponse GetContentLibrary(CDWKS.RevitAddon.Indexer2012.RevitFileServiceReference.GetContentLibraryRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IndexAutodeskFile", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class IndexAutodeskFileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public CDWKS.Model.Poco.Content.AutodeskFile file;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public bool overwrite;
        
        public IndexAutodeskFileRequest() {
        }
        
        public IndexAutodeskFileRequest(CDWKS.Model.Poco.Content.AutodeskFile file, bool overwrite) {
            this.file = file;
            this.overwrite = overwrite;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IndexAutodeskFileResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class IndexAutodeskFileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string IndexAutodeskFileResult;
        
        public IndexAutodeskFileResponse() {
        }
        
        public IndexAutodeskFileResponse(string IndexAutodeskFileResult) {
            this.IndexAutodeskFileResult = IndexAutodeskFileResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddTypeToFile", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddTypeToFileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public CDWKS.Model.Poco.Content.Item item;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string fileName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string owner;
        
        public AddTypeToFileRequest() {
        }
        
        public AddTypeToFileRequest(CDWKS.Model.Poco.Content.Item item, string fileName, string owner) {
            this.item = item;
            this.fileName = fileName;
            this.owner = owner;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddTypeToFileResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddTypeToFileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string AddTypeToFileResult;
        
        public AddTypeToFileResponse() {
        }
        
        public AddTypeToFileResponse(string AddTypeToFileResult) {
            this.AddTypeToFileResult = AddTypeToFileResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateLibraryTreeView", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UpdateLibraryTreeViewRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string tree;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string owner;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string revitVersion;
        
        public UpdateLibraryTreeViewRequest() {
        }
        
        public UpdateLibraryTreeViewRequest(string tree, string owner, string revitVersion) {
            this.tree = tree;
            this.owner = owner;
            this.revitVersion = revitVersion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateLibraryTreeViewResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UpdateLibraryTreeViewResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string UpdateLibraryTreeViewResult;
        
        public UpdateLibraryTreeViewResponse() {
        }
        
        public UpdateLibraryTreeViewResponse(string UpdateLibraryTreeViewResult) {
            this.UpdateLibraryTreeViewResult = UpdateLibraryTreeViewResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAutodeskFile", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetAutodeskFileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string fileName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string libraryName;
        
        public GetAutodeskFileRequest() {
        }
        
        public GetAutodeskFileRequest(string fileName, string libraryName) {
            this.fileName = fileName;
            this.libraryName = libraryName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAutodeskFileResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetAutodeskFileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public CDWKS.Model.Poco.Content.AutodeskFile GetAutodeskFileResult;
        
        public GetAutodeskFileResponse() {
        }
        
        public GetAutodeskFileResponse(CDWKS.Model.Poco.Content.AutodeskFile GetAutodeskFileResult) {
            this.GetAutodeskFileResult = GetAutodeskFileResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetContentLibrary", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetContentLibraryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string libraryName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string ownerId;
        
        public GetContentLibraryRequest() {
        }
        
        public GetContentLibraryRequest(string libraryName, string ownerId) {
            this.libraryName = libraryName;
            this.ownerId = ownerId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetContentLibraryResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetContentLibraryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int GetContentLibraryResult;
        
        public GetContentLibraryResponse() {
        }
        
        public GetContentLibraryResponse(int GetContentLibraryResult) {
            this.GetContentLibraryResult = GetContentLibraryResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAutodeskFileServiceChannel : CDWKS.RevitAddon.Indexer2012.RevitFileServiceReference.IAutodeskFileService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AutodeskFileServiceClient : System.ServiceModel.ClientBase<CDWKS.RevitAddon.Indexer2012.RevitFileServiceReference.IAutodeskFileService>, CDWKS.RevitAddon.Indexer2012.RevitFileServiceReference.IAutodeskFileService {
        
        public AutodeskFileServiceClient() {
        }
        
        public AutodeskFileServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AutodeskFileServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AutodeskFileServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AutodeskFileServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public CDWKS.RevitAddon.Indexer2012.RevitFileServiceReference.IndexAutodeskFileResponse IndexAutodeskFile(CDWKS.RevitAddon.Indexer2012.RevitFileServiceReference.IndexAutodeskFileRequest request) {
            return base.Channel.IndexAutodeskFile(request);
        }
        
        public CDWKS.RevitAddon.Indexer2012.RevitFileServiceReference.AddTypeToFileResponse AddTypeToFile(CDWKS.RevitAddon.Indexer2012.RevitFileServiceReference.AddTypeToFileRequest request) {
            return base.Channel.AddTypeToFile(request);
        }
        
        public CDWKS.RevitAddon.Indexer2012.RevitFileServiceReference.UpdateLibraryTreeViewResponse UpdateLibraryTreeView(CDWKS.RevitAddon.Indexer2012.RevitFileServiceReference.UpdateLibraryTreeViewRequest request) {
            return base.Channel.UpdateLibraryTreeView(request);
        }
        
        public CDWKS.RevitAddon.Indexer2012.RevitFileServiceReference.GetAutodeskFileResponse GetAutodeskFile(CDWKS.RevitAddon.Indexer2012.RevitFileServiceReference.GetAutodeskFileRequest request) {
            return base.Channel.GetAutodeskFile(request);
        }
        
        public CDWKS.RevitAddon.Indexer2012.RevitFileServiceReference.GetContentLibraryResponse GetContentLibrary(CDWKS.RevitAddon.Indexer2012.RevitFileServiceReference.GetContentLibraryRequest request) {
            return base.Channel.GetContentLibrary(request);
        }
    }
}
