//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Runtime.Serialization;

namespace CDWKS.Model.Poco.Content
{
    [DataContract]
    public class AutodeskFileIESFile
    {
        [DataMember]
        public  int Id
        {
            get;
            set;
        }
        [DataMember]
        public AutodeskFileTreeNode AutodeskFileTreeNode { get; set; }
        [DataMember]
        public IESFile IESFile { get; set; }
    	

     
    }
}
