//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Runtime.Serialization;

namespace CDWKS.Model.Poco.Content
{
    [DataContract]
    public class AutodeskFile
    {
        [DataMember]
        public  int Id
        {
            get;
            set;
        }
        [DataMember]
        public  string Name
        {
            get;
            set;
        }
        [DataMember]
        public  string MC_OwnerId
        {
            get;
            set;
        }
        [DataMember]
        public  int Version
        {
            get;
            set;
        }
        [DataMember]
        public  string TypeCatalogHeader
        {
            get;
            set;
        }
        [DataMember]
        public  ICollection<Image> Images { get; set; }

        [DataMember]
        public  ICollection<AutodeskFileTreeNode> AutodeskFileTreeNodes { get; set; }

        [DataMember]
        public  ICollection<Item> Items { get; set; }
    	

    
     
    }
}
